# uncompyle6 version 3.9.0 OKAY Decrypted
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
# Embedded file name: C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\shared.constants_matchmaking
from shared.constants import (DIA_DEFAULT_ACTIVE_BASES_AT_ONCE, DIA_DEFAULT_MAX_ACTIVE_DIAMONDS, DIA_DIAMONDS_TO_GET_FOR_MAP_ROTATION, MH_DEFAULT_NUMBER_OF_BASE_TO_ACTIVATE_AT_ONCE, MH_DEFAULT_BASE_AUTO_TIMEOUT, DEM_DEFAULT_BUILD_TIME, DIAMOND_LIFETIME, CRATE_SPAWN_DELAY, A2552, DEFAULT_RESPAWN_TIME, BOMB_EXPLOSION_FUSE, CLASS_SOLDIER, CLASS_SCOUT, CLASS_ENGINEER, CLASS_ROCKETEER, CLASS_MINER, CLASS_CLASSIC_SOLDIER, CLASS_GANGSTER_1, CLASS_SPECIALIST, CLASS_MEDIC)
from shared.constants_gamemode import ZOM_NOOF_FIRST_INFECTION_ZOMBIES, VIP_NOOF_ROUNDS_BEFORE_NEXT_MAP, ZOM_NOOF_ROUNDS_BEFORE_NEXT_MAP
from shared.constants import (SPADE_TOOL, GRENADE_TOOL, ANTIPERSONNEL_GRENADE_TOOL, SNOWBLOWER_TOOL, PICKAXE_TOOL, LANDMINE_TOOL, ROCKET_TURRET_TOOL, SUPERSPADE_TOOL, DRILLGUN_TOOL, DYNAMITE_TOOL, JETPACK_NORMAL, JETPACK2, KNIFE_TOOL, MINIGUN_TOOL, RPG_TOOL, RPG2_TOOL, MG_TOOL, PISTOL_TOOL, SNIPER_TOOL, RIFLE_TOOL, SMG_TOOL, SHOTGUN_TOOL, SHOTGUN2_TOOL, PREFAB_TOOL, SNIPER2_TOOL, CLASSIC_SPADE_TOOL, CLASSIC_GRENADE_TOOL, CLASSIC_SMG_TOOL, CLASSIC_SHOTGUN_TOOL, TOMMYGUN_TOOL, SNUB_PISTOL_TOOL, CROWBAR_TOOL, MOLOTOV_TOOL, BLOCK_TOOL, FLAREBLOCK_TOOL, JETPACK_ENGINEER, RIOTSTICK_TOOL, MACHETE_TOOL, MEDPACK_TOOL, RIOTSHIELD_TOOL, CHEMICALBOMB_TOOL, AUTOMATIC_PISTOL_TOOL, GRENADE_LAUNCHER_WEAPON_TOOL, RADAR_STATION_TOOL, A370, STICKY_GRENADE_TOOL, MINE_LAUNCHER_TOOL, C4_TOOL, ASSAULT_RIFLE_TOOL, LIGHT_MACHINE_GUN_TOOL, AUTO_SHOTGUN_TOOL, BLOCK_SUCKER_TOOL, DISGUISE_TOOL)
from shared.constants import MENU_FONT_COLOR, MENU_FONT_COLOR2
# DONE DECRYPTION
# NAMED CONSTANTS
LOBBYTYPE_UGC, LOBBYTYPE_MATCH = range(2)
# A2362 = CLASSIC - WTF
DLC_PACKS = ['STANDARD', 'A2362', 'MAFIA_PACK']
DEFAULT_PLAYLIST_TYPE = 'tdm'

GAME_RULES_NAMES = {
    "GENERAL": [
        "RULE_ENABLE_BLOCKS",
        "RULE_ENABLE_FLARE_BLOCKS",
        "RULE_ENABLE_PREFABS",
        "RULE_ONE_HIT_KILL",
        "RULE_ENABLE_GRAVESTONES",
        "RULE_ENABLE_CORPSE_EXPLOSION",
        "RULE_ENABLE_SNIPER_BEAM",
        "RULE_ENABLE_DEATH_CAM",
        "RULE_ENABLE_MINI_MAP",
        "RULE_ENABLE_SPECTATORS",
        "RULE_ENABLE_FALL_ON_WATER_DAMAGE",
        "RULE_RESPAWN_TIMES",
        "RULE_BLOCK_HEALTH",
        "RULE_WEAPON_DAMAGE",
        "RULE_SPAWN_PROTECTION_TIME",
        "RULE_CHARACTER_BLOCK_WALLETS",
        "RULE_CHARACTER_SPEED",
        "RULE_POINTS_FROM_TEABAGGING",
        "RULE_CRATES_SPAWN_TIME",
        "RULE_ENABLE_COLOUR_PICKER",
    ],
    "CLASSES": [
        "RULE_ENABLE_CLASS_COMMANDO",
        "RULE_ENABLE_CLASS_MARKSMAN",
        "RULE_ENABLE_CLASS_MINER",
        "RULE_ENABLE_CLASS_ENGINEER",
        "RULE_ENABLE_CLASS_ROCKETEER",
        "RULE_ENABLE_CLASS_SPECIALIST",
        "RULE_ENABLE_CLASS_MEDIC",
    ],
    "EQUIPMENT": [
        "RULE_ENABLE_EQUIPMENT_CLASSIC_SPADE",
        "RULE_ENABLE_EQUIPMENT_CLASSIC_GRENADE",
        "RULE_ENABLE_EQUIPMENT_SPADE",
        "RULE_ENABLE_EQUIPMENT_GRENADE",
        "RULE_ENABLE_EQUIPMENT_ANTIPERSONNEL_GRENADE",
        "RULE_ENABLE_EQUIPMENT_SNOWBLOWER",
        "RULE_ENABLE_EQUIPMENT_PICKAXE",
        "RULE_ENABLE_EQUIPMENT_LANDMINE",
        "RULE_ENABLE_EQUIPMENT_ROCKET_TURRET",
        "RULE_ENABLE_EQUIPMENT_GLIDE_JETPACK",
        "RULE_ENABLE_EQUIPMENT_JUMP_JETPACK",
        "RULE_ENABLE_EQUIPMENT_JETPACK",
        "RULE_ENABLE_EQUIPMENT_SUPER_SPADE",
        "RULE_ENABLE_EQUIPMENT_DRILL_CANNON",
        "RULE_ENABLE_EQUIPMENT_DYNAMITE",
        "RULE_ENABLE_EQUIPMENT_MEDPACK",
        "RULE_ENABLE_EQUIPMENT_CHEMICALBOMB",
        "RULE_ENABLE_EQUIPMENT_RADAR_STATION",
        "RULE_ENABLE_EQUIPMENT_C4",
        "RULE_ENABLE_EQUIPMENT_DISGUISE",
    ],
    "WEAPONS": [
        "RULE_ENABLE_WEAPON_KNIFE",
        "RULE_ENABLE_WEAPON_MINIGUN",
        "RULE_ENABLE_WEAPON_RPG",
        "RULE_ENABLE_WEAPON_TRIPLE_BARREL_RPG",
        "RULE_ENABLE_WEAPON_PISTOL",
        "RULE_ENABLE_WEAPON_SNIPER_RIFLE",
        "RULE_ENABLE_WEAPON_SNIPER_RIFLE2",
        "RULE_ENABLE_WEAPON_RIFLE",
        "RULE_ENABLE_WEAPON_DOUBLE_BARREL_SHOTGUN",
        "RULE_ENABLE_WEAPON_PUMP_ACTION_SHOTGUN",
        "RULE_ENABLE_WEAPON_SMG",
        "RULE_ENABLE_WEAPON_CLASSIC_SHOTGUN",
        "RULE_ENABLE_WEAPON_CLASSIC_SMG",
        "RULE_ENABLE_WEAPON_TOMMYGUN",
        "RULE_ENABLE_WEAPON_SNUB_PISTOL",
        "RULE_ENABLE_WEAPON_CROWBAR",
        "RULE_ENABLE_WEAPON_MOLOTOV",
        "RULE_ENABLE_WEAPON_RIOTSTICK",
        "RULE_ENABLE_WEAPON_MACHETE",
        "RULE_ENABLE_WEAPON_AUTOPISTOL",
        "RULE_ENABLE_WEAPON_GRENADE_LAUNCHER",
        "RULE_ENABLE_WEAPON_STICKY_GRENADE",
        "RULE_ENABLE_WEAPON_MINE_LAUNCHER",
        "RULE_ENABLE_WEAPON_ASSAULTRIFLE",
        "RULE_ENABLE_WEAPON_LIGHTMACHINEGUN",
        "RULE_ENABLE_WEAPON_AUTOSHOTGUN",
        "RULE_ENABLE_WEAPON_BLOCKSUCKER",
    ],
    "tdm": ["RULE_TDM_SCORE_TARGET"],
    "zom": [
        "RULE_ZOMBIE_NOOF_ROUNDS",
        "RULE_NOOF_FIRST_INFECTED_ZOMBIES",
        "RULE_CLASS_SPEED",
        "RULE_ZOMBIE_CLASS_DAMAGE",
    ],
    "vip": ["RULE_VIP_NOOF_ROUNDS", "RULE_VIP_HEALTH", "RULE_ENABLE_SUDDEN_DEATH"],
    "ctf": [
        "RULE_CTF_ENABLE_SHOOT_WITH_INTEL",
        "RULE_CTF_ENABLE_INTEL_RETURN_ON_TOUCH",
        "RULE_CTF_SCORE_TARGET",
        "RULE_CTF_ENABLE_INTEL_AUTO_RETURN",
    ],
    "cctf": [
        "RULE_CTF_ENABLE_SHOOT_WITH_INTEL",
        "RULE_CTF_ENABLE_INTEL_RETURN_ON_TOUCH",
        "RULE_CTF_SCORE_TARGET",
        "RULE_CTF_ENABLE_INTEL_AUTO_RETURN",
    ],
    "mh": ["RULE_MULTIHILL_MAX_ACTIVE_BASES", "RULE_BASE_ACTIVE_TIME"],
    "tc": ["RULE_TC_MAX_ACTIVE_BASES", "RULE_CAPTURE_RATE"],
    "dia": [
        "RULE_DIAMOND_MAX_ACTIVE_BASES",
        "RULE_DIA_SCORE_TARGET",
        "RULE_MAX_ACTIVE_DIAMONDS",
        "RULE_DIAMOND_LIFETIME",
    ],
    "dem": ["RULE_BUILD_STATE_LENGTH"],
    "oc": ["RULE_OCC_SCORE_TARGET", "RULE_MAX_ACTIVE_BOMBS", "RULE_BOMB_FUSE_TIME"],
}

NOOF_PLAYERS_LIST = ["2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "22", "24"]
MATCH_LENGTH_LIST = ["5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "90"]
NUMBERS_0_TO_60_STEP_5 = { "0": 0, "5": 5, "10": 10, "15": 15, "20": 20, "25": 25, "30": 30, "35": 35, "40": 40, "45": 45, "50": 50, "55": 55, "60": 60, }
NUMBERS_5_TO_60_STEP_5 = { "5": 5, "10": 10, "15": 15, "20": 20, "25": 25, "30": 30, "35": 35, "40": 40, "45": 45, "50": 50, "55": 55, "60": 60, }
NUMBERS_10_TO_60_STEP_5 = { "10": 10, "15": 15, "20": 20, "25": 25, "30": 30, "35": 35, "40": 40, "45": 45, "50": 50, "55": 55, "60": 60, }
NUMBERS_1_TO_10 = { "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, }
NUMBERS_10_TO_60_STEP_10 = {"10": 10, "20": 20, "30": 30, "40": 40, "50": 50, "60": 60}
SCORE_TARGETS_TO_WIN = { "OFF": False, "5": 5, "10": 10, "15": 15, "20": 20, "25": 25, "30": 30, "35": 35, "40": 40, "45": 45, "50": 50, "60": 60, "70": 70, "80": 80, "90": 90, "100": 100, "200": 200, }
SCORE_TARGETS_TO_WIN_OCC = { "OFF": False, "3": 3, "6": 6, "9": 9, "15": 15, "30": 30, "45": 45, "60": 60, "75": 75, "90": 90, "150": 150, }
NUMBERS_2_TO_5 = {"2": 2, "3": 3, "4": 4, "5": 5}
NUMBERS_1_TO_5 = {"1": 1, "2": 2, "3": 3, "4": 4, "5": 5}
NUMBERS_1_TO_3 = {"1": 1, "2": 2, "3": 3}

ON_OFF_VALUES = {"ON": True, "OFF": False}
LOW_NORMAL_MEDIUM_HIGH = {"50%": 0.5, "100%": 1.0, "150%": 1.5, "200%": 2.0}
LOW_NORMAL_HIGH = {"50%": 0.5, "100%": 1.0, "200%": 2.0}
LARGE_TIME_INTERVALS = { "30": 30, "60": 60, "90": 90, "120": 120, "180": 180, "240": 240, "300": 300, "360": 360, "420": 420, "480": 480, "540": 540, "600": 600, }
BUILD_TIME_LENGTHS = { "OFF": False, "10": 10, "20": 20, "30": 30, "40": 40, "50": 50, "60": 60, "70": 70, "80": 80, "90": 90, "100": 100, "110": 110, "120": 120, }
BOMB_FUSE_TIMES = {"5": 5, "10": 10, "15": 15, "20": 20}
SPARSE_PERCENTAGES = {"25%": 0.25, "50%": 0.5, "75%": 0.75}
SPAWN_PROTECTION_TIMES = {"OFF": 0.0, "1": 1.0, "2": 2.0, "3": 3.0}

A2663 = LOBBYTYPE_UGC
A2664 = LOBBYTYPE_MATCH
A2665 = DLC_PACKS
A2666 = DEFAULT_PLAYLIST_TYPE
A2667 = GAME_RULES_NAMES
A2668 = NOOF_PLAYERS_LIST
A2669 = MATCH_LENGTH_LIST
A2670 = NUMBERS_0_TO_60_STEP_5
A2671 = NUMBERS_5_TO_60_STEP_5
A2672 = NUMBERS_10_TO_60_STEP_5
A2673 = NUMBERS_1_TO_10
A2674 = NUMBERS_10_TO_60_STEP_10
A2675 = SCORE_TARGETS_TO_WIN
A2676 = SCORE_TARGETS_TO_WIN_OCC
A2677 = NUMBERS_2_TO_5
A2678 = NUMBERS_1_TO_5
A2679 = NUMBERS_1_TO_3
A2680 = ON_OFF_VALUES
A2681 = LOW_NORMAL_MEDIUM_HIGH
A2682 = LOW_NORMAL_HIGH
A2683 = LARGE_TIME_INTERVALS
A2684 = BUILD_TIME_LENGTHS
A2685 = BOMB_FUSE_TIMES
A2686 = SPARSE_PERCENTAGES
A2687 = SPAWN_PROTECTION_TIMES


GAME_RULES_LIST = {
    "RULE_ENABLE_WEAPON_KNIFE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER, CLASS_SCOUT],
    },
    "RULE_ENABLE_WEAPON_MINIGUN": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_SOLDIER]},
    "RULE_ENABLE_WEAPON_RPG": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_SOLDIER]},
    "RULE_ENABLE_WEAPON_TRIPLE_BARREL_RPG": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER],
    },
    "RULE_ENABLE_WEAPON_PISTOL": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_SCOUT]},
    "RULE_ENABLE_WEAPON_SNIPER_RIFLE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SCOUT],
    },
    "RULE_ENABLE_WEAPON_SNIPER_RIFLE2": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SCOUT],
    },
    "RULE_ENABLE_WEAPON_RIFLE": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_CLASSIC_SOLDIER]},
    "RULE_ENABLE_WEAPON_CLASSIC_SMG": {
        "default": "OFF",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_CLASSIC_SOLDIER],
    },
    "RULE_ENABLE_WEAPON_CLASSIC_SHOTGUN": {
        "default": "OFF",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_CLASSIC_SOLDIER],
    },
    "RULE_ENABLE_WEAPON_SMG": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_ENGINEER, CLASS_ROCKETEER]},
    "RULE_ENABLE_WEAPON_PUMP_ACTION_SHOTGUN": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_WEAPON_DOUBLE_BARREL_SHOTGUN": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_WEAPON_TOMMYGUN": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_GANGSTER_1]},
    "RULE_ENABLE_WEAPON_SNUB_PISTOL": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_GANGSTER_1],
    },
    "RULE_ENABLE_WEAPON_CROWBAR": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_GANGSTER_1]},
    "RULE_ENABLE_WEAPON_MOLOTOV": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_GANGSTER_1]},
    "RULE_ENABLE_WEAPON_RIOTSTICK": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MEDIC],
    },
    "RULE_ENABLE_WEAPON_MACHETE": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_SPECIALIST]},
    "RULE_ENABLE_WEAPON_RIOTSHIELD": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MEDIC],
    },
    "RULE_ENABLE_WEAPON_AUTOPISTOL": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SPECIALIST],
    },
    "RULE_ENABLE_WEAPON_GRENADE_LAUNCHER": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SPECIALIST],
    },
    "RULE_ENABLE_WEAPON_STICKY_GRENADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SPECIALIST],
    },
    "RULE_ENABLE_WEAPON_MINE_LAUNCHER": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER],
    },
    "RULE_ENABLE_WEAPON_ASSAULTRIFLE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER],
    },
    "RULE_ENABLE_WEAPON_LIGHTMACHINEGUN": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MEDIC],
    },
    "RULE_ENABLE_WEAPON_AUTOSHOTGUN": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SPECIALIST],
    },
    "RULE_ENABLE_WEAPON_BLOCKSUCKER": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_EQUIPMENT_CLASSIC_SPADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_CLASSIC_SOLDIER],
    },
    "RULE_ENABLE_EQUIPMENT_CLASSIC_GRENADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_CLASSIC_SOLDIER],
    },
    "RULE_ENABLE_EQUIPMENT_SPADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER, CLASS_ROCKETEER],
    },
    "RULE_ENABLE_EQUIPMENT_GRENADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER, CLASS_ROCKETEER],
    },
    "RULE_ENABLE_EQUIPMENT_ANTIPERSONNEL_GRENADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SOLDIER],
    },
    "RULE_ENABLE_EQUIPMENT_SNOWBLOWER": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER],
    },
    "RULE_ENABLE_EQUIPMENT_PICKAXE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER, CLASS_ROCKETEER, CLASS_SCOUT],
    },
    "RULE_ENABLE_EQUIPMENT_LANDMINE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SCOUT],
    },
    "RULE_ENABLE_EQUIPMENT_ROCKET_TURRET": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER, CLASS_ROCKETEER],
    },
    "RULE_ENABLE_EQUIPMENT_GLIDE_JETPACK": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ROCKETEER],
    },
    "RULE_ENABLE_EQUIPMENT_JUMP_JETPACK": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ROCKETEER],
    },
    "RULE_ENABLE_EQUIPMENT_JETPACK": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER],
    },
    "RULE_ENABLE_EQUIPMENT_SUPER_SPADE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_EQUIPMENT_DRILL_CANNON": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_EQUIPMENT_DYNAMITE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER],
    },
    "RULE_ENABLE_EQUIPMENT_MEDPACK": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MEDIC],
    },
    "RULE_ENABLE_EQUIPMENT_CHEMICALBOMB": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SPECIALIST],
    },
    "RULE_ENABLE_EQUIPMENT_RADAR_STATION": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_SCOUT],
    },
    "RULE_ENABLE_EQUIPMENT_C4": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_MINER]},
    "RULE_ENABLE_EQUIPMENT_DISGUISE": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_ENGINEER],
    },
    "RULE_ENABLE_CLASS_COMMANDO": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_MARKSMAN": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_MINER": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_ROCKETEER": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_ENGINEER": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_SPECIALIST": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CLASS_MEDIC": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_BLOCKS": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_FLARE_BLOCKS": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER, CLASS_ENGINEER, CLASS_ROCKETEER, CLASS_SCOUT, CLASS_SOLDIER, CLASS_GANGSTER_1],
    },
    "RULE_ENABLE_PREFABS": {
        "default": "ON",
        "values": ON_OFF_VALUES,
        "classes": [CLASS_MINER, CLASS_ENGINEER, CLASS_ROCKETEER, CLASS_SCOUT, CLASS_SOLDIER, CLASS_GANGSTER_1],
    },
    "RULE_ONE_HIT_KILL": {"default": "OFF", "values": ON_OFF_VALUES},
    "RULE_ENABLE_GRAVESTONES": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_CORPSE_EXPLOSION": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_SNIPER_BEAM": {"default": "ON", "values": ON_OFF_VALUES, "classes": [CLASS_SCOUT]},
    "RULE_ENABLE_DEATH_CAM": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_MINI_MAP": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_SPECTATORS": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_ENABLE_FALL_ON_WATER_DAMAGE": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_RESPAWN_TIMES": {"default": str(DEFAULT_RESPAWN_TIME), "values": A2670},
    "RULE_BLOCK_HEALTH": {"default": "100%", "values": A2682},
    "RULE_SPAWN_PROTECTION_TIME": {"default": "3", "values": A2687},
    "RULE_CHARACTER_BLOCK_WALLETS": {"default": "100%", "values": A2682},
    "RULE_CHARACTER_SPEED": {"default": "100%", "values": A2681},
    "RULE_WEAPON_DAMAGE": {"default": "100%", "values": A2682},
    "RULE_CRATES_SPAWN_TIME": {"default": str(CRATE_SPAWN_DELAY), "values": A2672},
    "RULE_POINTS_FROM_TEABAGGING": {"default": "OFF", "values": ON_OFF_VALUES},
    "RULE_ENABLE_COLOUR_PICKER": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_VOTES_REQUIRED_FOR_KICK": {"default": "50%", "values": A2686},
    "RULE_TDM_SCORE_TARGET": {"default": "200", "values": A2675},
    "RULE_MULTIHILL_MAX_ACTIVE_BASES": {"default": str(MH_DEFAULT_NUMBER_OF_BASE_TO_ACTIVATE_AT_ONCE), "values": A2678},
    "RULE_BASE_ACTIVE_TIME": {"default": str(MH_DEFAULT_BASE_AUTO_TIMEOUT), "values": A2683},
    "RULE_TC_MAX_ACTIVE_BASES": {"default": str(A2552), "values": A2677},
    "RULE_CAPTURE_RATE": {"default": "100%", "values": A2682},
    "RULE_ZOMBIE_NOOF_ROUNDS": {"default": str(ZOM_NOOF_ROUNDS_BEFORE_NEXT_MAP), "values": A2678},
    "RULE_NOOF_FIRST_INFECTED_ZOMBIES": {"default": str(ZOM_NOOF_FIRST_INFECTION_ZOMBIES), "values": A2678},
    "RULE_CLASS_SPEED": {"default": "100%", "values": A2682},
    "RULE_ZOMBIE_CLASS_DAMAGE": {"default": "100%", "values": A2682},
    "RULE_CTF_SCORE_TARGET": {"default": "5", "values": A2673},
    "RULE_CTF_ENABLE_SHOOT_WITH_INTEL": {"default": "OFF", "values": ON_OFF_VALUES},
    "RULE_CTF_ENABLE_INTEL_AUTO_RETURN": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_CTF_ENABLE_INTEL_RETURN_ON_TOUCH": {"default": "OFF", "values": ON_OFF_VALUES},
    "RULE_CTF_ENABLE_INTEL_IN_OWN_BASE_TO_SCORE": {"default": "OFF", "values": ON_OFF_VALUES},
    "RULE_DIAMOND_MAX_ACTIVE_BASES": {"default": str(DIA_DEFAULT_ACTIVE_BASES_AT_ONCE), "values": A2678},
    "RULE_DIA_SCORE_TARGET": {"default": str(DIA_DIAMONDS_TO_GET_FOR_MAP_ROTATION), "values": A2671},
    "RULE_MAX_ACTIVE_DIAMONDS": {"default": str(DIA_DEFAULT_MAX_ACTIVE_DIAMONDS), "values": A2678},
    "RULE_DIAMOND_LIFETIME": {"default": str(DIAMOND_LIFETIME), "values": A2674},
    "RULE_VIP_NOOF_ROUNDS": {"default": str(VIP_NOOF_ROUNDS_BEFORE_NEXT_MAP), "values": A2678},
    "RULE_VIP_HEALTH": {"default": "100%", "values": A2682},
    "RULE_ENABLE_SUDDEN_DEATH": {"default": "ON", "values": ON_OFF_VALUES},
    "RULE_BUILD_STATE_LENGTH": {"default": str(DEM_DEFAULT_BUILD_TIME), "values": A2684},
    "RULE_OCC_SCORE_TARGET": {"default": "30", "values": A2676},
    "RULE_MAX_ACTIVE_BOMBS": {"default": "1", "values": A2679},
    "RULE_BOMB_FUSE_TIME": {"default": str(BOMB_EXPLOSION_FUSE), "values": A2685},
}
A2688 = GAME_RULES_LIST

JOIN_SUCCESS, JOIN_ERROR_DOESNT_EXIST, JOIN_ERROR_NOT_ALLOWED, JOIN_ERROR_FULL, JOIN_ERROR_UNKNOWN, JOIN_ERROR_BANNED, JOIN_ERROR_LIMITED_USER, JOIN_ERROR_CLAN_DISABLED, JOIN_ERROR_COMMUNITY_BANNED, JOIN_ERROR_MEMBER_BLOCKING_YOU, JOIN_ERROR_YOU_BLOCKED_MEMBER, JOIN_ERROR_NO_RANKING_LOBBY, JOIN_ERROR_NO_RANKING_USER, JOIN_ERROR_RANK_OUT_OF_RANGE = range(14)
LOBBY_CHATLINE_BACKGROUND = (79, 80, 64, 255)
LOBBY_COLOUR_LEADER = (255, 59, 59, 255)
LOBBY_COLOUR_LOCAL = MENU_FONT_COLOR
LOBBY_COLOUR_LOCAL_LEADER = LOBBY_COLOUR_LEADER
LOBBY_COLOUR_INGAME = MENU_FONT_COLOR
LOBBY_COLOUR_MEMBER = MENU_FONT_COLOR
LOBBY_COLOUR_CHAT = MENU_FONT_COLOR
LOBBY_COLOUR_CHAT_EVENT = MENU_FONT_COLOR2
A2703 = LOBBY_CHATLINE_BACKGROUND
A2704 = LOBBY_COLOUR_LEADER
A2705 = LOBBY_COLOUR_LOCAL
A2706 = LOBBY_COLOUR_LOCAL_LEADER
A2707 = LOBBY_COLOUR_INGAME
A2708 = LOBBY_COLOUR_MEMBER
A2709 = LOBBY_COLOUR_CHAT
A2710 = LOBBY_COLOUR_CHAT_EVENT
A2689 = JOIN_SUCCESS
A2690 = JOIN_ERROR_DOESNT_EXIST
A2691 = JOIN_ERROR_NOT_ALLOWED
A2692 = JOIN_ERROR_FULL
A2693 = JOIN_ERROR_UNKNOWN
A2694 = JOIN_ERROR_BANNED
A2695 = JOIN_ERROR_LIMITED_USER
A2696 = JOIN_ERROR_CLAN_DISABLED
A2697 = JOIN_ERROR_COMMUNITY_BANNED
A2698 = JOIN_ERROR_MEMBER_BLOCKING_YOU
A2699 = JOIN_ERROR_YOU_BLOCKED_MEMBER
A2700 = JOIN_ERROR_NO_RANKING_LOBBY
A2701 = JOIN_ERROR_NO_RANKING_USER
A2702 = JOIN_ERROR_RANK_OUT_OF_RANGE


RULE_TO_TOOL_MAP = {
    "RULE_ENABLE_EQUIPMENT_SPADE": SPADE_TOOL,
    "RULE_ENABLE_EQUIPMENT_GRENADE": GRENADE_TOOL,
    "RULE_ENABLE_EQUIPMENT_ANTIPERSONNEL_GRENADE": ANTIPERSONNEL_GRENADE_TOOL,
    "RULE_ENABLE_EQUIPMENT_SNOWBLOWER": SNOWBLOWER_TOOL,
    "RULE_ENABLE_EQUIPMENT_PICKAXE": PICKAXE_TOOL,
    "RULE_ENABLE_EQUIPMENT_LANDMINE": LANDMINE_TOOL,
    "RULE_ENABLE_EQUIPMENT_ROCKET_TURRET": ROCKET_TURRET_TOOL,
    "RULE_ENABLE_EQUIPMENT_GLIDE_JETPACK": JETPACK2,
    "RULE_ENABLE_EQUIPMENT_JUMP_JETPACK": JETPACK_NORMAL,
    "RULE_ENABLE_EQUIPMENT_JETPACK": JETPACK_ENGINEER,
    "RULE_ENABLE_EQUIPMENT_SUPER_SPADE": SUPERSPADE_TOOL,
    "RULE_ENABLE_EQUIPMENT_DRILL_CANNON": DRILLGUN_TOOL,
    "RULE_ENABLE_EQUIPMENT_DYNAMITE": DYNAMITE_TOOL,
    "RULE_ENABLE_EQUIPMENT_CLASSIC_SPADE": CLASSIC_SPADE_TOOL,
    "RULE_ENABLE_EQUIPMENT_CLASSIC_GRENADE": CLASSIC_GRENADE_TOOL,
    "RULE_ENABLE_WEAPON_KNIFE": KNIFE_TOOL,
    "RULE_ENABLE_WEAPON_MINIGUN": MINIGUN_TOOL,
    "RULE_ENABLE_WEAPON_RPG": RPG_TOOL,
    "RULE_ENABLE_WEAPON_TRIPLE_BARREL_RPG": RPG2_TOOL,
    "RULE_ENABLE_WEAPON_PISTOL": PISTOL_TOOL,
    "RULE_ENABLE_WEAPON_SNIPER_RIFLE": SNIPER_TOOL,
    "RULE_ENABLE_WEAPON_SNIPER_RIFLE2": SNIPER2_TOOL,
    "RULE_ENABLE_WEAPON_RIFLE": RIFLE_TOOL,
    "RULE_ENABLE_WEAPON_SMG": SMG_TOOL,
    "RULE_ENABLE_WEAPON_PUMP_ACTION_SHOTGUN": SHOTGUN_TOOL,
    "RULE_ENABLE_WEAPON_DOUBLE_BARREL_SHOTGUN": SHOTGUN2_TOOL,
    "RULE_ENABLE_WEAPON_CLASSIC_SMG": CLASSIC_SMG_TOOL,
    "RULE_ENABLE_WEAPON_CLASSIC_SHOTGUN": CLASSIC_SHOTGUN_TOOL,
    "RULE_ENABLE_WEAPON_TOMMYGUN": TOMMYGUN_TOOL,
    "RULE_ENABLE_WEAPON_SNUB_PISTOL": SNUB_PISTOL_TOOL,
    "RULE_ENABLE_WEAPON_CROWBAR": CROWBAR_TOOL,
    "RULE_ENABLE_WEAPON_MOLOTOV": MOLOTOV_TOOL,
    "RULE_ENABLE_PREFABS": PREFAB_TOOL,
    "RULE_ENABLE_FLARE_BLOCKS": FLAREBLOCK_TOOL,
    "RULE_ENABLE_BLOCKS": BLOCK_TOOL,
    "RULE_ENABLE_WEAPON_RIOTSTICK": RIOTSTICK_TOOL,
    "RULE_ENABLE_WEAPON_MACHETE": MACHETE_TOOL,
    "RULE_ENABLE_EQUIPMENT_MEDPACK": MEDPACK_TOOL,
    "RULE_ENABLE_WEAPON_RIOTSHIELD": RIOTSHIELD_TOOL,
    "RULE_ENABLE_WEAPON_AUTOPISTOL": AUTOMATIC_PISTOL_TOOL,
    "RULE_ENABLE_EQUIPMENT_CHEMICALBOMB": CHEMICALBOMB_TOOL,
    "RULE_ENABLE_WEAPON_GRENADE_LAUNCHER": GRENADE_LAUNCHER_WEAPON_TOOL,
    "RULE_ENABLE_EQUIPMENT_RADAR_STATION": RADAR_STATION_TOOL,
    "RULE_ENABLE_EQUIPMENT_PARACHUTE_NORMAL": A370,
    "RULE_ENABLE_WEAPON_STICKY_GRENADE": STICKY_GRENADE_TOOL,
    "RULE_ENABLE_WEAPON_MINE_LAUNCHER": MINE_LAUNCHER_TOOL,
    "RULE_ENABLE_EQUIPMENT_C4": C4_TOOL,
    "RULE_ENABLE_WEAPON_ASSAULTRIFLE": ASSAULT_RIFLE_TOOL,
    "RULE_ENABLE_WEAPON_LIGHTMACHINEGUN": LIGHT_MACHINE_GUN_TOOL,
    "RULE_ENABLE_WEAPON_AUTOSHOTGUN": AUTO_SHOTGUN_TOOL,
    "RULE_ENABLE_WEAPON_BLOCKSUCKER": BLOCK_SUCKER_TOOL,
    "RULE_ENABLE_EQUIPMENT_DISGUISE": DISGUISE_TOOL,
}

RULE_TO_CLASS_MAP = {
    "RULE_ENABLE_CLASS_COMMANDO": CLASS_SOLDIER,
    "RULE_ENABLE_CLASS_MARKSMAN": CLASS_SCOUT,
    "RULE_ENABLE_CLASS_MINER": CLASS_MINER,
    "RULE_ENABLE_CLASS_ROCKETEER": CLASS_ROCKETEER,
    "RULE_ENABLE_CLASS_ENGINEER": CLASS_ENGINEER,
    "RULE_ENABLE_CLASS_SPECIALIST": CLASS_SPECIALIST,
    "RULE_ENABLE_CLASS_MEDIC": CLASS_MEDIC,
}

Steam_Lobby_Accessibility_Private = 0
Steam_Lobby_Accessibility_FriendsOnly = 1
Steam_Lobby_Accessibility_Public = 2
Steam_Lobby_Accessibility_Invisible = 3


# NEW ENCRYPTED CONSTANTS
A2711 = RULE_TO_TOOL_MAP
A2712 = RULE_TO_CLASS_MAP
A2713 = Steam_Lobby_Accessibility_Private
A2714 = Steam_Lobby_Accessibility_FriendsOnly
A2715 = Steam_Lobby_Accessibility_Public
A2716 = Steam_Lobby_Accessibility_Invisible
# okay decompiling out\shared.constants_matchmaking.pyc
