# uncompyle6 version 3.9.2 Fixed Decrypted
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\shared.constants_gamemode
# DONE DECRYPTION
# New ENCRYPTED Constants map to the original Constants

MODE_NORMAL, MODE_DEMOLITION, MODE_ZOMBIE, MODE_MULTIHILL, MODE_OCCUPATION, MODE_DIAMONDMINE, MODE_TDM, MODE_VIP, MODE_CTF, MODE_TERRITORY, MODE_TUTORIAL, MODE_CCTF, MODE_UGC = range(13)

A2435 = MODE_NORMAL
A2436 = MODE_DEMOLITION
A2437 = MODE_ZOMBIE
A2438 = MODE_MULTIHILL
A2439 = MODE_OCCUPATION
A2440 = MODE_DIAMONDMINE
A2441 = MODE_TDM
A2442 = MODE_VIP
A2443 = MODE_CTF
A2444 = MODE_TERRITORY
A2445 = MODE_TUTORIAL
A2446 = MODE_CCTF
A2447 = MODE_UGC



MODE_MAP_TITLES = {
    'zom': 'ZOMBIE_MODE_TITLE', 
    'tdm': 'TDM_TITLE', 
    'dia': 'DIAMOND_MINE_TITLE', 
    'oc': 'OCCUPATION_MODE_TITLE', 
    'dem': 'DEMOLITION_TITLE', 
    'mh': 'MULTIHILL_TITLE', 
    'vip': 'VIP_MODE_TITLE', 
    'ctf': 'CTF_TITLE', 
    'tc': 'TC_TITLE', 
    'cctf': 'CLASSIC_CTF_TITLE', 
    'tut': 'TUTORIAL_MODE_TITLE', 
    'ugc': 'MAP_CREATOR'
}

A2448 = MODE_MAP_TITLES 

MODE_DESCRIPTIONS = {
    'dem': 'DEMOLITION_DESCRIPTION', 
    'zom': 'ZOMBIE_MODE_DESCRIPTION', 
    'mh': 'MULTIHILL_DESCRIPTION', 
    'oc': 'OCCUPATION_MODE_DESCRIPTION', 
    'dia': 'DIAMOND_MINE_DESCRIPTION', 
    'tdm': 'TDM_DESCRIPTION', 
    'vip': 'VIP_MODE_DESCRIPTION', 
    'ctf': 'CTF_DESCRIPTION', 
    'tc': 'TC_DESCRIPTION', 
    'tut': 'TUTORIAL_DESCRIPTION', 
    'cctf': 'CTF_DESCRIPTION', 
    'ugc': 'UGC_DESCRIPTION'
}

A2449 = MODE_DESCRIPTIONS

MODE_MODE_IDS = {
    'nor': MODE_NORMAL, 
    'zom': MODE_ZOMBIE, 
    'tdm': MODE_TDM, 
    'dia': MODE_DIAMONDMINE, 
    'oc': MODE_OCCUPATION, 
    'dem': MODE_DEMOLITION, 
    'mh': MODE_MULTIHILL, 
    'vip': MODE_VIP, 
    'ctf': MODE_CTF, 
    'tc': MODE_TERRITORY, 
    'cctf': MODE_CTF, 
    'tut': MODE_TUTORIAL, 
    'ugc': MODE_UGC
}

A2450 = MODE_MODE_IDS

MODE_IDS_MODE = {
    MODE_NORMAL: 'nor', 
    MODE_ZOMBIE: 'zom', 
    MODE_TDM: 'tdm', 
    MODE_DIAMONDMINE: 'dia', 
    MODE_OCCUPATION: 'oc', 
    MODE_DEMOLITION: 'dem', 
    MODE_MULTIHILL: 'mh', 
    MODE_VIP: 'vip', 
    MODE_CTF: 'ctf', 
    MODE_TERRITORY: 'tc', 
    MODE_TUTORIAL: 'tut', 
    MODE_UGC: 'ugc'
}

A2451 = MODE_IDS_MODE

GAME_MODE_CALLBACK_EMPTY_SERVER_TIMEOUT, GAME_MODE_CALLBACK_BUILDING_MODE, GAME_MODE_CALLBACK_WATCH_EXPLOSION, GAME_MODE_CALLBACK_TIMER, GAME_MODE_CALLBACK_TIMER_MUSIC, GAME_MODE_CALLBACK_GAME_ENDED_SCORES, GAME_MODE_CALLBACK_TIMEOUT, GAME_MODE_CALLBACK_TIMEOUT_MUSIC, GAME_MODE_CALLBACK_ADVANCE_DELAY, GAME_MODE_CALLBACK_SPAWNING_BOMB, GAME_MODE_CALLBACK_VIP_SUDDEN_DEATH_DELAY, GAME_MODE_CALLBACK_ZOMBIE_PICK, GAME_MODE_CALLBACK_ZOMBIE_PICK_SOUND, GAME_MODE_CALLBACK_ZOMBIE_WIN_END, GAME_MODE_CALLBACK_SURVIVOR_WIN, GAME_MODE_CALLBACK_SURVIVOR_WIN_MUSIC, GAME_MODE_CALLBACK_SURVIVOR_WIN_END, GAME_MODE_CALLBACK_WIN_START, GAME_MODE_CALLBACK_BASE_PICK, GAME_MODE_CALLBACK_MAP_VOTE_CLOSE = range(20)
A2452 = GAME_MODE_CALLBACK_EMPTY_SERVER_TIMEOUT
A2453 = GAME_MODE_CALLBACK_BUILDING_MODE
A2454 = GAME_MODE_CALLBACK_WATCH_EXPLOSION
A2455 = GAME_MODE_CALLBACK_TIMER
A2456 = GAME_MODE_CALLBACK_TIMER_MUSIC
A2457 = GAME_MODE_CALLBACK_GAME_ENDED_SCORES
A2458 = GAME_MODE_CALLBACK_TIMEOUT
A2459 = GAME_MODE_CALLBACK_TIMEOUT_MUSIC
A2460 = GAME_MODE_CALLBACK_ADVANCE_DELAY
A2461 = GAME_MODE_CALLBACK_SPAWNING_BOMB
A2462 = GAME_MODE_CALLBACK_VIP_SUDDEN_DEATH_DELAY
A2463 = GAME_MODE_CALLBACK_ZOMBIE_PICK
A2464 = GAME_MODE_CALLBACK_ZOMBIE_PICK
A2465 = GAME_MODE_CALLBACK_ZOMBIE_WIN_END
A2466 = GAME_MODE_CALLBACK_SURVIVOR_WIN
A2467 = GAME_MODE_CALLBACK_SURVIVOR_WIN_MUSIC
A2468 = GAME_MODE_CALLBACK_SURVIVOR_WIN_END
A2469 = GAME_MODE_CALLBACK_WIN_START
A2470 = GAME_MODE_CALLBACK_BASE_PICK
A2471 = GAME_MODE_CALLBACK_MAP_VOTE_CLOSE

ZONE_ICON_NONE, ZONE_ICON_DEMOLITION, ZONE_ICON_MULTIHILL, ZONE_ICON_OCCUPATION, ZONE_ICON_DIAMONDMINE, ZONE_ICON_VIP, ZONE_ICON_CTF, ZONE_ICON_TERRITORY_A, ZONE_ICON_TERRITORY_B, ZONE_ICON_TERRITORY_C, ZONE_ICON_TERRITORY_D, ZONE_ICON_TERRITORY_E, ZONE_ICON_TERRITORY_F, ZONE_ICON_TERRITORY_G, ZONE_ICON_TERRITORY_H, ZONE_ICON_TERRITORY_I, ZONE_ICON_TERRITORY_J, ZONE_ICON_SPAWN = range(18)

A2472 = ZONE_ICON_NONE
A2473 = ZONE_ICON_DEMOLITION
A2474 = ZONE_ICON_MULTIHILL
A2475 = ZONE_ICON_OCCUPATION
A2476 = ZONE_ICON_DIAMONDMINE
A2477 = ZONE_ICON_VIP
A2478 = ZONE_ICON_CTF
A2479 = ZONE_ICON_TERRITORY_A
A2480 = ZONE_ICON_TERRITORY_B
A2481 = ZONE_ICON_TERRITORY_C
A2482 = ZONE_ICON_TERRITORY_D
A2483 = ZONE_ICON_TERRITORY_E
A2484 = ZONE_ICON_TERRITORY_F
A2485 = ZONE_ICON_TERRITORY_G
A2486 = ZONE_ICON_TERRITORY_H
A2487 = ZONE_ICON_TERRITORY_I
A2488 = ZONE_ICON_TERRITORY_J
A2489 = ZONE_ICON_SPAWN

MODE_ZONE_ICONS = {
    ZONE_ICON_NONE: [],
    ZONE_ICON_DEMOLITION: ["minimap_base", "base_icon"],
    ZONE_ICON_MULTIHILL: ["minimap_multihill", "MultiHill"],
    ZONE_ICON_OCCUPATION: ["minimap_occupation_target", "OccupationTarget"],
    ZONE_ICON_DIAMONDMINE: ["minimap_diamond_dropoff", "diamond_dropoff"],
    ZONE_ICON_VIP: ["vip_icon_256x256", "vip_icon_256x256"],
    ZONE_ICON_CTF: ["minimap_base", "base_icon"],
    ZONE_ICON_TERRITORY_A: ["tc_minimap_a", "tc_billboard_a"],
    ZONE_ICON_TERRITORY_B: ["tc_minimap_b", "tc_billboard_b"],
    ZONE_ICON_TERRITORY_C: ["tc_minimap_c", "tc_billboard_c"],
    ZONE_ICON_TERRITORY_D: ["tc_minimap_d", "tc_billboard_d"],
    ZONE_ICON_TERRITORY_E: ["tc_minimap_e", "tc_billboard_e"],
    ZONE_ICON_TERRITORY_F: ["tc_minimap_f", "tc_billboard_f"],
    ZONE_ICON_TERRITORY_G: ["tc_minimap_g", "tc_billboard_g"],
    ZONE_ICON_TERRITORY_H: ["tc_minimap_g", "tc_billboard_g"],
    ZONE_ICON_TERRITORY_I: ["tc_minimap_g", "tc_billboard_g"],
    ZONE_ICON_TERRITORY_J: ["tc_minimap_g", "tc_billboard_g"],
    ZONE_ICON_SPAWN: ["minimap_spawn", "spawn_icon"],
}


A2490 = MODE_ZONE_ICONS

PROGRESSBAR_ICON_BASE, PROGRESSBAR_ICON_DIAMOND = range(2)

A2491 = PROGRESSBAR_ICON_BASE
A2492 = PROGRESSBAR_ICON_DIAMOND

MODE_TITLE = {
    MODE_NORMAL: None, 
    MODE_DEMOLITION: 'DEMOLITION_TITLE', 
    MODE_ZOMBIE: 'ZOMBIE_MODE_TITLE', 
    MODE_MULTIHILL: 'MULTIHILL_TITLE', 
    MODE_OCCUPATION: 'OCCUPATION_MODE_TITLE', 
    MODE_DIAMONDMINE: 'DIAMOND_MINE_TITLE', 
    MODE_TDM: 'TDM_TITLE', 
    MODE_VIP: 'VIP_MODE_TITLE', 
    MODE_CTF: 'CTF_TITLE', 
    MODE_TERRITORY: 'TC_TITLE', 
    MODE_TUTORIAL: 'TUTORIAL_MODE_TITLE', 
    MODE_UGC: 'MAP_CREATOR'
}

A2493 = MODE_TITLE

LOADING_MENU_TAB_INTERVAL = 3.0
A2494 = LOADING_MENU_TAB_INTERVAL
LOADING_MENU_TAB_LOOP = True
A2495 = LOADING_MENU_TAB_LOOP
SCREENSHOT_CAMERA_SWITCH_INTERVAL = 5.0
A2496 = SCREENSHOT_CAMERA_SWITCH_INTERVAL
SCREENSHOT_CAMERA_GAME_LENGTH = 60
A2497 = SCREENSHOT_CAMERA_GAME_LENGTH
SCREENSHOT_CAMERA_PAN_DISTANCE = -5.0
A2498 = SCREENSHOT_CAMERA_PAN_DISTANCE
SCREENSHOT_CAMERA_PAN_TIME = 5.0
A2499 = SCREENSHOT_CAMERA_PAN_TIME
TIMEOUT_MUSIC_LENGTH = 61.0
A2500 = TIMEOUT_MUSIC_LENGTH
TIME_AFTER_WIN_BEFORE_SCORES = 5.0 
A2501 = TIME_AFTER_WIN_BEFORE_SCORES
TIME_AFTER_MAP_VOTE_START_BEFORE_END = 10.0
A2502 = TIME_AFTER_MAP_VOTE_START_BEFORE_END
DEFAULT_GAME_LENGTH = 900
A2503 = DEFAULT_GAME_LENGTH
CLASSIC_GAME_LENGTH = 2700
A2504 = CLASSIC_GAME_LENGTH
GENERIC_SCORE_KILL = 100
A2505 = GENERIC_SCORE_KILL
GENERIC_SCORE_HEADSHOT = 150
A2506 = GENERIC_SCORE_HEADSHOT
GENERIC_SCORE_MELEE = 150
A2507 = GENERIC_SCORE_MELEE
GENERIC_SCORE_ASSIST = 50
A2508 = GENERIC_SCORE_ASSIST
GENERIC_SCORE_REVENGE = 50
A2509 = GENERIC_SCORE_REVENGE
GENERIC_SCORE_PAYBACK = 50
A2510 = GENERIC_SCORE_PAYBACK
GENERIC_SCORE_RELOAD = 50
A2511 = GENERIC_SCORE_RELOAD
GENERIC_SCORE_DEFEND = 50
A2512 = GENERIC_SCORE_DEFEND
GENERIC_SCORE_SUICIDE = -100
A2513 = GENERIC_SCORE_SUICIDE
GENERIC_SCORE_TEAMKILL = -100
A2514 = GENERIC_SCORE_TEAMKILL
GENERIC_ASSIST_PERCENTAGE = 50.0
A2515 = GENERIC_ASSIST_PERCENTAGE

# WTF
NORMAL_SCORE_TEABAG = 2
CLASSIC_SCORE_TEABAG = 2

# Back to normal
TDM_GAME_LENGTH = DEFAULT_GAME_LENGTH
A2516 = TDM_GAME_LENGTH
TDM_TEAM_SCORE_FOR_KILL = 1
A2517 = TDM_TEAM_SCORE_FOR_KILL
TDM_SCORE_DISTRACT = 50
A2518 = TDM_SCORE_DISTRACT
ZOM_ROUND_TIME = 600.0
A2519 = ZOM_ROUND_TIME
ZOM_NOOF_ROUNDS_BEFORE_NEXT_MAP = 3
A2520 = ZOM_NOOF_ROUNDS_BEFORE_NEXT_MAP
ZOM_EXTRA_INDIVIDUAL_SCORE_FOR_SURVIVAL = 200
A2521 = ZOM_EXTRA_INDIVIDUAL_SCORE_FOR_SURVIVAL
ZOM_NOOF_FIRST_INFECTION_ZOMBIES = 2
A2522 = ZOM_NOOF_FIRST_INFECTION_ZOMBIES
ZOM_TIME_BEFORE_FIRST_INFECTION = 60
A2523 = ZOM_TIME_BEFORE_FIRST_INFECTION
ZOM_TIME_AFTER_ZOMBIE_WIN_BEFORE_SCORES = 5.0
A2524 = ZOM_TIME_AFTER_ZOMBIE_WIN_BEFORE_SCORES
ZOM_TIME_AFTER_SURVIVOR_WIN_BEFORE_SCORES = 5.0
A2525 = ZOM_TIME_AFTER_SURVIVOR_WIN_BEFORE_SCORES
ZOM_GAMEMODE_TIMEOUT = 600.0
A2526 = ZOM_GAMEMODE_TIMEOUT
ZOM_RESPAWN_AS_ZOMBIE_TIME = 0.0
A2527 = ZOM_RESPAWN_AS_ZOMBIE_TIME
ZOM_SCORE_SURVIVE = 50
A2528 = ZOM_SCORE_SURVIVE
ZOM_SCORE_SURVIVE_INTERVAL = 10.0
A2529 = ZOM_SCORE_SURVIVE_INTERVAL
ZOM_SCORE_LASTMAN = 150
A2530 = ZOM_SCORE_LASTMAN
ZOM_SCORE_LASTMAN_INTERVAL = 5.0
A2531 = ZOM_SCORE_LASTMAN_INTERVAL
ZOM_SCORE_KILL_SURVIVOR = 100
A2532 = ZOM_SCORE_KILL_SURVIVOR
ZOM_SCORE_LASTMAN_ZOMBIEKILL = 50
A2533 = ZOM_SCORE_LASTMAN_ZOMBIEKILL
MH_GAME_LENGTH = 1500
A2534 = MH_GAME_LENGTH
MH_TEAM_SCORE_PER_TICK = 1
A2535 = MH_TEAM_SCORE_PER_TICK
MH_TEAM_SCORE_TICK_RATE = 1.0
A2536 = MH_TEAM_SCORE_TICK_RATE
MH_DEFAULT_BASE_AUTO_TIMEOUT = 240
A2537 = MH_DEFAULT_BASE_AUTO_TIMEOUT
MH_TIME_BETWEEN_BASE_ACTIVATIONS = 10.0
A2538 = MH_TIME_BETWEEN_BASE_ACTIVATIONS
MH_DEFAULT_NUMBER_OF_BASE_TO_ACTIVATE_AT_ONCE = 1
A2539 = MH_DEFAULT_NUMBER_OF_BASE_TO_ACTIVATE_AT_ONCE
MH_SCORE_OCCUPY = 150
A2540 = MH_SCORE_OCCUPY
MH_SCORE_OCCUPY_INTERVAL = 5.0
A2541 = MH_SCORE_OCCUPY_INTERVAL
MH_SCORE_DEFEND = 100
A2542 = MH_SCORE_DEFEND
MH_SCORE_ASSAULT = 50
A2543 = MH_SCORE_ASSAULT
MH_SCORE_FIRST = 250
A2544 = MH_SCORE_FIRST
MH_SCORE_CLAIM = 150
A2545 = MH_SCORE_CLAIM
MH_SCORE_CONTROL = 100
A2546 = MH_SCORE_CONTROL
MH_SCORE_CONTEST = 50
A2547 = MH_SCORE_CONTEST
TC_GAME_LENGTH = 1500
A2548 = TC_GAME_LENGTH
TC_CAPTURE_TICK_RATE = 0.5
A2549 = TC_CAPTURE_TICK_RATE
TC_CAPTURE_RATE = [115, 116, 117, 118, 119]
A2550 = TC_CAPTURE_RATE
TC_NEW_TEAM_ENTERS_SHOUT_COOLDOWN = 5.0
A2551 = TC_NEW_TEAM_ENTERS_SHOUT_COOLDOWN
TC_DEFAULT_BASE_COUNT_TO_USE = 5
A2552 = TC_DEFAULT_BASE_COUNT_TO_USE
TC_SCORE_OCCUPY_INTERVAL = 5.0
A2553 = TC_SCORE_OCCUPY_INTERVAL
TC_SCORE_OCCUPY_PERHILL = 35
A2554 = TC_SCORE_OCCUPY_PERHILL
TC_SCORE_CLAIM = 150
A2555 = TC_SCORE_CLAIM
TC_SCORE_CONTROL = 100
A2556 = TC_SCORE_CONTROL
TC_SCORE_KILL_KILLERINHILL = 100
A2557 = TC_SCORE_KILL_KILLERINHILL
TC_SCORE_KILL_VICTIMINHILL = 50
A2558 = TC_SCORE_KILL_VICTIMINHILL
TC_SCORE_CONTEND_INTERVAL = 5.0
A2559 = TC_SCORE_CONTEND_INTERVAL
TC_SCORE_CONTEND_HILL = 25
A2560 = TC_SCORE_CONTEND_HILL
TC_BASENAMES = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
A2561 = TC_BASENAMES
OC_GAME_LENGTH = DEFAULT_GAME_LENGTH
A2562 = OC_GAME_LENGTH
OC_TEAM_SCORE_FOR_KILLING_CARRIER = 1
A2563 = OC_TEAM_SCORE_FOR_KILLING_CARRIER
OC_TEAM_SCORE_FOR_BOMB_EXPLOSION_IN_BASE = 3
A2564 = OC_TEAM_SCORE_FOR_BOMB_EXPLOSION_IN_BASE
OC_EXTRA_INDIVIDUAL_SCORE_FOR_KILL_CARRIER = OC_TEAM_SCORE_FOR_KILLING_CARRIER - 1
A2565 = OC_EXTRA_INDIVIDUAL_SCORE_FOR_KILL_CARRIER
OC_BOMB_RESPAWN_TIME_ON_EXPLOSION = 10.0
A2566 = OC_BOMB_RESPAWN_TIME_ON_EXPLOSION
OC_SCORE_FOR_BOMB_EXPLOSION_IN_BASE = 50
A2567 = OC_SCORE_FOR_BOMB_EXPLOSION_IN_BASE
OC_SCORE_CARRY_SCORE = 50
A2568 = OC_SCORE_CARRY_SCORE
OC_SCORE_CARRY_INTERVAL = 5.0
A2569 = OC_SCORE_CARRY_INTERVAL
OC_SCORE_DISTRACT = 100
A2570 = OC_SCORE_DISTRACT
OC_SCORE_CARRIER_DEFEND = 100
A2571 = OC_SCORE_CARRIER_DEFEND
OC_CARRIER_THREAT_RADIUS = 10.0
A2572 = OC_CARRIER_THREAT_RADIUS
OC_SCORE_DEFEND = 50
A2573 = OC_SCORE_DEFEND
OC_THREAT_RADIUS = 20.0
A2574 = OC_THREAT_RADIUS
OC_SCORE_ASSAULT = 100
A2575 = OC_SCORE_ASSAULT
OC_SCORE_INTERCEPT = 50
A2576 = OC_SCORE_INTERCEPT
OC_SCORE_SURVIVE = 50
A2577 = OC_SCORE_SURVIVE
OC_SCORE_OCCUPY_SCORE = 50
A2578 = OC_SCORE_OCCUPY_SCORE
OC_SCORE_OCCUPY_INTERVAL = 5.0
A2579 = OC_SCORE_OCCUPY_INTERVAL
OC_SCORE_FOR_DISPOSAL = 25
A2580 = OC_SCORE_FOR_DISPOSAL
OC_SCORE_FOR_DISPOSAL_INTERCEPT = 25
A2581 = OC_SCORE_FOR_DISPOSAL_INTERCEPT
VIP_NOOF_ROUNDS_BEFORE_NEXT_MAP = 3
A2582 = VIP_NOOF_ROUNDS_BEFORE_NEXT_MAP
VIP_GAME_LENGTH = DEFAULT_GAME_LENGTH
A2583 = VIP_GAME_LENGTH
VIP_TEAM_SCORE_FOR_KILL = 10
A2584 = VIP_TEAM_SCORE_FOR_KILL
VIP_SCORE_VIP_KILL_CONSTANT = 0
A2585 = VIP_SCORE_VIP_KILL_CONSTANT
VIP_SCORE_VIP_KILL_PERCENT = 10
A2586 = VIP_SCORE_VIP_KILL_PERCENT
VIP_SCORE_OWN_VIP_KILL = 0
A2587 = VIP_SCORE_OWN_VIP_KILL
VIP_SCORE_KILL_AS_VIP = 100
A2588 = VIP_SCORE_KILL_AS_VIP
VIP_MINIMUM_TEAM_SIZE_TO_START = 1
A2589 = VIP_MINIMUM_TEAM_SIZE_TO_START
VIP_SELECTION_DELAY = 3.0
A2590 = VIP_SELECTION_DELAY
VIP_SCORE_LIVEVIP_SCORE = 50
A2591 = VIP_SCORE_LIVEVIP_SCORE
VIP_SCORE_LIVEVIP_INTERVAL = 10.0
A2592 = VIP_SCORE_LIVEVIP_INTERVAL
VIP_SCORE_ESCORT_SCORE = 10
A2593 = VIP_SCORE_ESCORT_SCORE
VIP_SCORE_ESCORT_INTERVAL = 5.0
A2594 = VIP_SCORE_ESCORT_INTERVAL
VIP_ESCORT_RADIUS = 15.0
A2595 = VIP_ESCORT_RADIUS
VIP_ESCORT_HYSTERESIS = 10.0
A2596 = VIP_ESCORT_HYSTERESIS
VIP_THREAT_RADIUS = 20.0
A2597 = VIP_THREAT_RADIUS
VIP_SCORE_DISTRACT = 50
A2598 = VIP_SCORE_DISTRACT
VIP_SCORE_DEFEND = 150
A2599 = VIP_SCORE_DEFEND

#WTF
VIP_SELECTION_DELAY = 10.0
A2590 = VIP_SELECTION_DELAY

VIP_SUDDEN_DEATH_DAMAGE = 1
A2600 = VIP_SUDDEN_DEATH_DAMAGE
VIP_SUDDEN_DEATH_DAMAGE_FREQUENCY = 1
A2601 = VIP_SUDDEN_DEATH_DAMAGE_FREQUENCY
VIP_SUDDEN_DEATH_TIME = 60
A2602 = VIP_SUDDEN_DEATH_TIME
VIP_SUDDEN_DEATH_DELAY_AFTER_VIP_KILL = 5
A2603 = VIP_SUDDEN_DEATH_DELAY_AFTER_VIP_KILL
DIA_GAME_LENGTH = DEFAULT_GAME_LENGTH
A2604 = DIA_GAME_LENGTH
DIA_DEFAULT_MAX_ACTIVE_DIAMONDS = 2
A2605 = DIA_DEFAULT_MAX_ACTIVE_DIAMONDS
DIA_HIGHEST_DIAMOND_CHANCE = 1.0 / 100.0
A2606 = DIA_HIGHEST_DIAMOND_CHANCE
DIA_LOWEST_DIAMOND_CHANCE = 1.0 / 500.0
A2607 = DIA_LOWEST_DIAMOND_CHANCE
DIA_INDIVIDUAL_SCORE_FOR_MINED_DIAMOND = 10
A2608 = DIA_INDIVIDUAL_SCORE_FOR_MINED_DIAMOND
DIA_INDIVIDUAL_SCORE_FOR_CASHED_IN_DIAMOND = 100
A2609 = DIA_INDIVIDUAL_SCORE_FOR_CASHED_IN_DIAMOND
DIA_DEFAULT_ACTIVE_BASES_AT_ONCE = 1
A2610 = DIA_DEFAULT_ACTIVE_BASES_AT_ONCE
DIA_DIAMONDS_TO_GET_FOR_MAP_ROTATION = 15
A2611 = DIA_DIAMONDS_TO_GET_FOR_MAP_ROTATION
DIA_DIAMONDS_TO_TRIGGER_MAP_VOTE = DIA_DIAMONDS_TO_GET_FOR_MAP_ROTATION - 3
A2612 = DIA_DIAMONDS_TO_TRIGGER_MAP_VOTE
DIA_TIME_BETWEEN_DIAMOND_SPAWN = 15
A2613 = DIA_TIME_BETWEEN_DIAMOND_SPAWN
DIA_SCORE_CARRY_SCORE = 50
A2614 = DIA_SCORE_CARRY_SCORE
DIA_SCORE_CARRY_INTERVAL = 5.0
A2615 = DIA_SCORE_CARRY_INTERVAL
DIA_SCORE_ESCORT_SCORE = 10
A2616 = DIA_SCORE_ESCORT_SCORE
DIA_SCORE_ESCORT_INTERVAL = 5.0
A2617 = DIA_SCORE_ESCORT_INTERVAL
DIA_ESCORT_RADIUS = 15.0
A2618 = DIA_ESCORT_RADIUS
DIA_ESCORT_HYSTERESIS = 10.0
A2619 = DIA_ESCORT_HYSTERESIS
DIA_SCORE_DISTRACT = 100
A2620 = DIA_SCORE_DISTRACT
DIA_SCORE_CARRIER_DEFEND = 100
A2621 = DIA_SCORE_CARRIER_DEFEND
DIA_CARRIER_THREAT_RADIUS = 10.0
A2622 = DIA_CARRIER_THREAT_RADIUS
DIA_SCORE_DEFEND = 50
A2623 = DIA_SCORE_DEFEND
DIA_THREAT_RADIUS = 20.0
A2624 = DIA_THREAT_RADIUS
DIA_SCORE_ASSAULT = 50
A2625 = DIA_SCORE_ASSAULT
DIA_SCORE_INTERCEPT = 50
A2626 = DIA_SCORE_INTERCEPT
DEM_GAME_LENGTH = DEFAULT_GAME_LENGTH
A2627 = DEM_GAME_LENGTH
DEM_DEFAULT_BUILD_TIME = 30
A2628 = DEM_DEFAULT_BUILD_TIME
DEM_REPAIR_WARNING_PERCENT = 75
A2629 = DEM_REPAIR_WARNING_PERCENT
DEM_TIME_TO_WAIT_FOR_AIRSTRIKE = 5.0
A2630 = DEM_TIME_TO_WAIT_FOR_AIRSTRIKE
DEM_BUILD_SPACE_PERCENT = 0
A2631 = DEM_BUILD_SPACE_PERCENT
DEM_SCORE_DESTROY_SCORE = 25
A2632 = DEM_SCORE_DESTROY_SCORE
DEM_SCORE_DESTROY_INTERVAL = 50
A2633 = DEM_SCORE_DESTROY_INTERVAL
DEM_SCORE_REPAIR_SCORE = 50
A2634 = DEM_SCORE_REPAIR_SCORE
DEM_SCORE_REPAIR_INTERVAL = 50
A2635 = DEM_SCORE_REPAIR_INTERVAL
DEM_ALLOW_SCORE_REPAIR_BUILDINGMODE = False
A2636 = DEM_ALLOW_SCORE_REPAIR_BUILDINGMODE
DEM_SCORE_DEFEND = 100
A2637 = DEM_SCORE_DEFEND
DEM_SCORE_ASSAULT = 50
A2638 = DEM_SCORE_ASSAULT
CTF_GAME_LENGTH = DEFAULT_GAME_LENGTH * 2.0
A2639 = CTF_GAME_LENGTH
CTF_CLASSIC_GAME_LENGTH = CLASSIC_GAME_LENGTH * 2.0
A2640 = CTF_CLASSIC_GAME_LENGTH
CTF_TEAM_SCORE_FOR_CAPTURED_INTEL = 1
A2641 = CTF_TEAM_SCORE_FOR_CAPTURED_INTEL
CTF_INDIVIDUAL_SCORE_FOR_CAPTURED_INTEL = 10
A2642 = CTF_INDIVIDUAL_SCORE_FOR_CAPTURED_INTEL
CTF_INDIVIDUAL_SCORE_FOR_RETURNING_INTEL = 1
A2643 = CTF_INDIVIDUAL_SCORE_FOR_RETURNING_INTEL
CTF_INTEL_RETURN_TIME = 60
A2644 = CTF_INTEL_RETURN_TIME
CLASSIC_CTF_BASE_CAPTURE_DISTANCE = 5
A2645 = CLASSIC_CTF_BASE_CAPTURE_DISTANCE
CLASSIC_CTF_INTEL_MIN_RADIUS_FROM_BASE = 3
A2646 = CLASSIC_CTF_INTEL_MIN_RADIUS_FROM_BASE
CTF_SCORE_CARRY_SCORE = 50
A2647 = CTF_SCORE_CARRY_SCORE
CTF_SCORE_CARRY_INTERVAL = 5.0
A2648 = CTF_SCORE_CARRY_INTERVAL
CTF_SCORE_ESCORT_SCORE = 10
A2649 = CTF_SCORE_ESCORT_SCORE
CTF_SCORE_ESCORT_INTERVAL = 5.0
A2650 = CTF_SCORE_ESCORT_INTERVAL
CTF_ESCORT_RADIUS = 20.0
A2651 = CTF_ESCORT_RADIUS
CTF_ESCORT_HYSTERESIS = 1.0
A2652 = CTF_ESCORT_HYSTERESIS
CTF_SCORE_DISTRACT = 100
A2653 = CTF_SCORE_DISTRACT
CTF_SCORE_CARRIER_DEFEND = 100
A2654 = CTF_SCORE_CARRIER_DEFEND
CTF_CARRIER_THREAT_RADIUS = 10.0
A2655 = CTF_CARRIER_THREAT_RADIUS
CTF_SCORE_DEFEND = 50
A2656 = CTF_SCORE_DEFEND
CTF_THREAT_RADIUS = 20.0
A2657 = CTF_THREAT_RADIUS
CTF_SCORE_ASSAULT = 50
A2658 = CTF_SCORE_ASSAULT
CTF_SCORE_ASSAULT_ENEMY = 50
A2659 = CTF_SCORE_ASSAULT_ENEMY
CTF_SCORE_INTERCEPT = 50
A2660 = CTF_SCORE_INTERCEPT
CTF_SCORE_CLAIM = 100
A2661 = CTF_SCORE_CLAIM
DEFAULT_MODE_GAME_LENGTH = {
    'zom': ZOM_ROUND_TIME, 
    'tdm': TDM_GAME_LENGTH, 
    'dia': DIA_GAME_LENGTH, 
    'oc': OC_GAME_LENGTH, 
    'dem': DEM_GAME_LENGTH, 
    'mh': MH_GAME_LENGTH, 
    'vip': VIP_GAME_LENGTH, 
    'ctf': CTF_GAME_LENGTH, 
    'tc': TC_GAME_LENGTH, 
    'cctf': CTF_CLASSIC_GAME_LENGTH, 
    'tut': DEFAULT_GAME_LENGTH
}

A2662 = DEFAULT_MODE_GAME_LENGTH
